apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-gateway
  template:
    metadata:
      labels:
        app: server-gateway
    spec:
      containers:
        - name: server-gateway
          image: aminabakkali/server-gateway
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-gateway
spec:
  type: LoadBalancer
  selector:
    app: server-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080