apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gateway
  labels:
    app: server-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-gateway
  template:
    metadata:
      labels:
        app: server-gateway
    spec:
      containers:
        - name: server-gateway
          image: aminabakkali/server-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: server-gateway